# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUIV2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(660, 562)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox1DPlot = QtWidgets.QGroupBox(Form)
        self.groupBox1DPlot.setObjectName("groupBox1DPlot")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox1DPlot)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.linePlot0 = PlotWidget(self.groupBox1DPlot)
        self.linePlot0.setObjectName("linePlot0")
        self.gridLayout_3.addWidget(self.linePlot0, 6, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox1DPlot)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox1DPlot)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_2.addWidget(self.lineEdit_5)
        self.checkBoxNotch50Hz = QtWidgets.QCheckBox(self.groupBox1DPlot)
        self.checkBoxNotch50Hz.setObjectName("checkBoxNotch50Hz")
        self.horizontalLayout_2.addWidget(self.checkBoxNotch50Hz)
        self.comboBoxRawDurations = QtWidgets.QComboBox(self.groupBox1DPlot)
        self.comboBoxRawDurations.setObjectName("comboBoxRawDurations")
        self.comboBoxRawDurations.addItem("")
        self.comboBoxRawDurations.addItem("")
        self.comboBoxRawDurations.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBoxRawDurations)
        self.pushButtonRawParamsSubmit = QtWidgets.QPushButton(self.groupBox1DPlot)
        self.pushButtonRawParamsSubmit.setObjectName("pushButtonRawParamsSubmit")
        self.horizontalLayout_2.addWidget(self.pushButtonRawParamsSubmit)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox1DPlot, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox2DPlot = QtWidgets.QGroupBox(Form)
        self.groupBox2DPlot.setObjectName("groupBox2DPlot")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox2DPlot)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBoxSpecTP9 = QtWidgets.QCheckBox(self.groupBox2DPlot)
        self.checkBoxSpecTP9.setObjectName("checkBoxSpecTP9")
        self.horizontalLayout_3.addWidget(self.checkBoxSpecTP9)
        self.checkBoxSpecAF7 = QtWidgets.QCheckBox(self.groupBox2DPlot)
        self.checkBoxSpecAF7.setObjectName("checkBoxSpecAF7")
        self.horizontalLayout_3.addWidget(self.checkBoxSpecAF7)
        self.checkBoxSpecAF8 = QtWidgets.QCheckBox(self.groupBox2DPlot)
        self.checkBoxSpecAF8.setObjectName("checkBoxSpecAF8")
        self.horizontalLayout_3.addWidget(self.checkBoxSpecAF8)
        self.checkBoxSpecTP10 = QtWidgets.QCheckBox(self.groupBox2DPlot)
        self.checkBoxSpecTP10.setObjectName("checkBoxSpecTP10")
        self.horizontalLayout_3.addWidget(self.checkBoxSpecTP10)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.imgPlot0 = PlotWidget(self.groupBox2DPlot)
        self.imgPlot0.setObjectName("imgPlot0")
        self.gridLayout_2.addWidget(self.imgPlot0, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox2DPlot)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox2DPlot)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_4.addWidget(self.lineEdit_3)
        self.label = QtWidgets.QLabel(self.groupBox2DPlot)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox2DPlot)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_4.addWidget(self.lineEdit_4)
        self.label_2 = QtWidgets.QLabel(self.groupBox2DPlot)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.comboBoxSpecDurations = QtWidgets.QComboBox(self.groupBox2DPlot)
        self.comboBoxSpecDurations.setObjectName("comboBoxSpecDurations")
        self.comboBoxSpecDurations.addItem("")
        self.comboBoxSpecDurations.addItem("")
        self.comboBoxSpecDurations.addItem("")
        self.comboBoxSpecDurations.addItem("")
        self.comboBoxSpecDurations.addItem("")
        self.comboBoxSpecDurations.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBoxSpecDurations)
        self.pushButtonSpecParamsSubmit = QtWidgets.QPushButton(self.groupBox2DPlot)
        self.pushButtonSpecParamsSubmit.setObjectName("pushButtonSpecParamsSubmit")
        self.horizontalLayout_4.addWidget(self.pushButtonSpecParamsSubmit)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.groupBox2DPlot)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.threeDplots = GLViewWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(28)
        sizePolicy.setHeightForWidth(self.threeDplots.sizePolicy().hasHeightForWidth())
        self.threeDplots.setSizePolicy(sizePolicy)
        self.threeDplots.setMinimumSize(QtCore.QSize(300, 100))
        self.threeDplots.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.threeDplots.setAcceptDrops(True)
        self.threeDplots.setObjectName("threeDplots")
        self.gridLayout_5.addWidget(self.threeDplots, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.groupBox)
        self.gridLayout.addLayout(self.horizontalLayout_5, 3, 0, 1, 1)
        self.groupBoxNetwork = QtWidgets.QGroupBox(Form)
        self.groupBoxNetwork.setObjectName("groupBoxNetwork")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBoxNetwork)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBoxNetwork)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_6.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBoxNetwork)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_6.addWidget(self.lineEdit_2)
        self.pushButton = QtWidgets.QPushButton(self.groupBoxNetwork)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBoxNetwork)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_6.addWidget(self.pushButton_2)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBoxNetwork, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox1DPlot.setTitle(_translate("Form", "Raw data"))
        self.label_4.setText(_translate("Form", "Value range:"))
        self.checkBoxNotch50Hz.setText(_translate("Form", "Notch 50Hz"))
        self.comboBoxRawDurations.setItemText(0, _translate("Form", "1 sec."))
        self.comboBoxRawDurations.setItemText(1, _translate("Form", "5 sec."))
        self.comboBoxRawDurations.setItemText(2, _translate("Form", "10 sec."))
        self.pushButtonRawParamsSubmit.setText(_translate("Form", "Submit"))
        self.groupBox2DPlot.setTitle(_translate("Form", "Spectrogram"))
        self.checkBoxSpecTP9.setText(_translate("Form", "TP9"))
        self.checkBoxSpecAF7.setText(_translate("Form", "AF7"))
        self.checkBoxSpecAF8.setText(_translate("Form", "AF8"))
        self.checkBoxSpecTP10.setText(_translate("Form", "TP10"))
        self.label_3.setText(_translate("Form", "Frequency range: from"))
        self.label.setText(_translate("Form", "to"))
        self.label_2.setText(_translate("Form", "Hz"))
        self.comboBoxSpecDurations.setItemText(0, _translate("Form", "1 sec."))
        self.comboBoxSpecDurations.setItemText(1, _translate("Form", "30 sec."))
        self.comboBoxSpecDurations.setItemText(2, _translate("Form", "1 min."))
        self.comboBoxSpecDurations.setItemText(3, _translate("Form", "10 min."))
        self.comboBoxSpecDurations.setItemText(4, _translate("Form", "30 min."))
        self.comboBoxSpecDurations.setItemText(5, _translate("Form", "60 min."))
        self.pushButtonSpecParamsSubmit.setText(_translate("Form", "Submit"))
        self.groupBox.setTitle(_translate("Form", "3D Plot"))
        self.groupBoxNetwork.setTitle(_translate("Form", "Network and settings"))
        self.pushButton.setText(_translate("Form", "PushButton"))
        self.pushButton_2.setText(_translate("Form", "PushButton"))

from pyqtgraph import PlotWidget
from pyqtgraph.opengl import GLViewWidget
